name: Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create docker image name
        id: docker-image
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          BRANCH_NAME=$(echo $BRANCH_NAME | tr '/' '_')
          IMAGE_NAME=${BRANCH_NAME}_${{ github.sha }}
          echo "::set-output name=IMAGE_NAME::$IMAGE_NAME"
      - name: Extract repository name
        id: extract-repository-name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "::set-output name=REPO_NAME::$REPO_NAME"
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.LAURABOT_DOCKER_USERNAME }}
          password: ${{ secrets.LAURABOT_DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.LAURABOT_DOCKER_USERNAME }}/${{ steps.extract-repository-name.outputs.REPO_NAME }}:${{ steps.docker-image.outputs.IMAGE_NAME }}
            docker.io/${{ secrets.LAURABOT_DOCKER_USERNAME }}/${{ steps.extract-repository-name.outputs.REPO_NAME }}:latest